week-11/day-4/TodoApp/TodoApp/Controllers/TodoController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TodoApp.Models;
using TodoApp.Models.Dtos;
using TodoApp.Services;

namespace TodoApp.Controllers
{
    public class TodoController : Controller
    {
        private readonly IAssigneeService assigneeService;
        private readonly ITodoService todoService;

        public TodoController(IAssigneeService assigneeService, ITodoService todoService)
        {
            this.assigneeService = assigneeService;
            this.todoService = todoService;
        }

        public IEnumerable<SelectListItem> GetAssignees()
        {
            return assigneeService.FindAssignees.Select(a =>
                              new SelectListItem
                              {
                                  Value = a.AssigneeId.ToString(),
                                  Text = a.Name
                              }).ToList();
        }

        [HttpGet("/Todo/Add")]
        public IActionResult RenderAdd()
        {
            var model = new AssigneeView
            {
                Names = GetAssignees()
            };
            return View("Add", model);
        }

        [HttpPost("/Todo/Add")]
        public IActionResult Add(AddTodoDTO addTodoDTO)
        {
            todoService.AddTodo(addTodoDTO);
            return Redirect("/");
        }

        [HttpPost("/Todo/Delete")]
        public IActionResult Delete(long id)
        {
            todoService.DeleteTodo(id);
            return Redirect("/");
        }
    }
}

week-11/day-4/TodoApp/TodoApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>@ViewBag.Title</title>
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <div class="container">
        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">TodoApp Home</a>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li><a asp-area="" asp-controller="Todo" asp-action="Add">Add Todo</a></li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Assignee <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a asp-area="" asp-controller="Assignee" asp-action="List">List of Assignees</a></li>
                                <li><a asp-area="" asp-controller="Assignee" asp-action="Add">New Assignee</a></li>
                            </ul>
                        </li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">

                        @if (User.Identity.IsAuthenticated)
                        {
                        <li>
                            <form method="post" asp-controller="Account" asp-action="Logout">
                                <button type="submit" style="width:auto"
                                        class="nav-link btn btn-link py-0">
                                    @User.Identity.Name, Logout
                                </button>
                            </form>
                        </li>
                        }
                        else
                        {
                            <li>
                                <a asp-controller="Account" asp-action="Login">Login</a>
                            </li>
                            <li>
                                <a asp-controller="Account" asp-action="Register">Sign Up</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
        @RenderBody()
    </div>
    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>
</body>
</html>